; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; PlatformIO Project Configuration File
[env]
upload_protocol = teensy-cli
framework = arduino

lib_deps = 
    https://github.com/bolderflight/invensense-imu.git
    https://github.com/arduino-libraries/SD.git
    https://github.com/PaulStoffregen/PWMServo.git
    https://github.com/finitespace/BME280.git
    https://github.com/stm32duino/ISM330DHCX.git
    https://github.com/sparkfun/SparkFun_MMC5983MA_Magnetometer_Arduino_Library.git
    https://github.com/earlephilhower/arduino-littlefs-upload.git
    https://github.com/hideakitai/ArduinoEigen.git
    https://github.com/bblanchon/ArduinoJson.git

; ---------------------------
; Firmware environment (Teensy 4.1)
; ---------------------------
[env:teensy41]
platform = teensy
board = teensy41