name: CI
on:
  push:
  pull_request:

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build clang clang-tidy

      - name: Generate compile_commands.json
        working-directory: code
        run: meson setup build --wipe

      - name: Generate compile_commands.json
        working-directory: code
        run: meson compile -C build/

      - name: Run the executable for one second to make sure it doesn't crash and burn on startup
        run: timeout 1s ./code/build/firmware/firmware || true

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit checks
        run: pre-commit run --all-files